name: "triggers - exercice 3"
on:
  #a completer
  pull_request:
    paths:
    - '**.yml'
    - '!**/test/**.yml'
    
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - run: echo "je verifie les fichiers YAML"
