name: "triggers - exercice2"
on:
  #a completer
  push:
  pull_request:
    branches: "main"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - run: echo "je vérifie que le code compile bien"
    
